name: Delete PR Image

on:
  pull_request:
    types:
    - closed
    branches:
    - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  clean-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - id: details
        uses: kpfleming/composite-actions/image-details@74c01bb4d399a98545e8cdc5826d832b7917ac6b # v3.1.0
        with:
          base_image: python:trixie-main

      - uses: kpfleming/composite-actions/delete-pr-image@74c01bb4d399a98545e8cdc5826d832b7917ac6b # v3.1.0
        with:
          image_registry: ${{ steps.details.outputs.image_registry }}
          registry_account: ${{ steps.details.outputs.registry_account }}
          registry_token: ${{ secrets.FORGE_API_TOKEN }}
          repo_name: ${{ steps.details.outputs.repo_name }}
